const PERCENTAGE_ITEM_IN_VIEW = 25/100;
const TIME_IN_VIEW_MS = 1000;
const URL_M2_END_POINT = 'http://localhost:8080';

export {
    PERCENTAGE_ITEM_IN_VIEW,
    TIME_IN_VIEW_MS,
    URL_M2_END_POINT
};